# Site settings
url: https://ericakatrak.github.io
title: Erica Katrak - designer
description: "Erica Katrak works at the intersection of design, research, strategy, and code."
keywords: "erica, katrak, design, designer, user experience, product design"
name: Erica Katrak

# Footer settings
footer:
  copyright: Erica Katrak

# Build settings
markdown: kramdown
permalink: none
