# Site settings
url: https://ericakatrak.github.io
title: Erica Katrak - designer
description: "Erica Katrak works at the intersection of research, strategy, design, and code."
keywords: "erica, katrak, design, designer, prefer, user experience, product design"
name: Erica Katrak

# Footer settings
footer:
  copyright: Erica Katrak

# Build settings
markdown: kramdown
permalink: none
